### ISSUE TITLE
Topic: Larger community contributions (8 votes)

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx-standup#12]
Talking points:
* Successfully finished:
  * System.Security.Cryptography.Xml.**SignedXml** - [#4278](https://github.com/dotnet/corefx/issues/4278)
  * System.IO.**SerialPort** - [#984](https://github.com/dotnet/corefx/issues/984)
* In progress:
  * System.**DirectoryServices** - Linux/Mac port [#2089](https://github.com/dotnet/corefx/issues/2089) (not all libs possible) and test coverage [#20669](https://github.com/dotnet/corefx/issues/20669)
    * See [all DirectoryServices issues](https://github.com/dotnet/corefx/labels/area-System.DirectoryServices)
    * Challenge of server-client test infra (also useful for Networking and WCF)
  * System.**Drawing** - [20325](https://github.com/dotnet/corefx/issues/20325) (reusing Mono / shims to existing OSS libraries / test covergae)
* Future:
  * Potentially: Parts of new Networking stack - Fast SslStream [#21371](https://github.com/dotnet/corefx/issues/21371) and parts of Technical roadmap [#21533](https://github.com/dotnet/corefx/issues/21533)
  * System.Data?
* Questions:
  * How best to announce them to contributors? (Standups, blog posts, Annoucnement issues, tweets, anything else?)
  * Is anyone interested to participate?

**Comment by steji113** [comment]
I am very much interested in helping to contribute to larger or high cost / high impact issues. I believe System.IO.SerialPort is a perfect example of such an issue. It seemed like it had fairly good demand from the community but was not able to be funded by the MS CoreFX team. I wonder if a Twitter account or a label on Announcement issues could best be used to communicate the demand for working on a particular topic. Perhaps more seasoned community contributors could take on the roll of driving the project through to completion and enlisting implementation help from others.

As an example, I recently stumbled upon dotnet/corefx#8655 and realized that it had been open for a year and was also blocking various scenarios for consumers of .NET Core. However, it took quite a bit of digging through the issues, hunting for the right one to work on.

**Comment by karelz** [comment]
Discussed in standup on 2017/9/22 - see #29 for more details and recording link.
