### ISSUE TITLE
Topic: Discussion: General communication from CoreFX / .NET team (7 votes)

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx-standup#21]
Talking points:
* What we use today:
  * 'Announcement' issues on CoreFX repo, e.g.:
    * Engineering changes [#15135](https://github.com/dotnet/corefx/issues/15135)
    * .NET Core 2.0 ZBB [#17619](https://github.com/dotnet/corefx/issues/17619),
    * 2.0 Data call for help [#19970](https://github.com/dotnet/corefx/issues/19970),
    * CoreFX CI legs update [#21135](https://github.com/dotnet/corefx/issues/21135)
    * Networking stack - Technical roadmap [#21533](https://github.com/dotnet/corefx/issues/21533)
  * General issues, e.g.:
    * Update docs to be new-contributor friendly [#17534](https://github.com/dotnet/corefx/issues/17534)
    * APIs out of scope in CoreFX - 'CoreFXExtension's repo? [#20902](https://github.com/dotnet/corefx/issues/20902)
    * Regular alpha versions of vnext product [#20911](https://github.com/dotnet/corefx/issues/20911)
    * Faster SslStream [#21371](https://github.com/dotnet/corefx/issues/21371) ... larger investment
  * Usually together with tweets
  * This repo https://github.com/dotnet/corefx-standup-temp - tagging all participants manually
* Questions:
  * How do you learn about these things? Whic channel do you use?
    * Do you use Twitter [@corefxissues](https://twitter.com/corefxissues) feed?
    * Do you monitor entire CoreFX repo via GitHub notifications?
    * Do you check new issues manually on GitHub?
    * Anything else?
  * Is the communication channel effective? Would you like to see different?
  * Feedback / suggestion on the kind of announcements / communications? What would you improve?
    * Are issues sufficient?
    * Is regular contributors standup valuable?
    * Should we accompany it with regular "what's happening" blog posts? (e.g. on .NET blog)
    * anything else?
  * How can we be more open? (what works well, what doesn't, suggestions)

**Comment by karelz** [comment]
Covered in [2017/6/26 - 1st standup](https://github.com/dotnet/corefx-standup/blob/master/Standups/2017-06.md)

**Comment by shaggygi** [comment]
@karelz 

> How can we be more open?

I would like to see a blog or wiki explaining vision/direction around the embedded/IoT space.  I understand this is just one part and others might want to see more details on other topics.  I also understand there is some gray area as it hinges on resources/timelines/progress of different technologies.  However, it would be nice to see thoughts on related work that is currently being addressed and some basic expectations.  Below are some quick examples that could be discussed...

1. What are some successes that have been accomplished by the Tizen focus?
2. What are some advances and hurdles that teams are seeing with the work for [arch-arm32](https://github.com/dotnet/coreclr/issues?q=is%3Aissue+is%3Aopen+label%3Aarch-arm32)?
3. What are some prototypes and  embedded boards (e.g. RPi, Beagle Bone, etc.) that can now run .NET Core and plans to bring better tooling to Visual Studio for them?
4. Better hardware APIs to take advantage of board features (I2C, serial, Bluetooth, etc.)?  Understanding this would be more from community and not directly in CoreFx.
5. Improved Docker support and micro-service scenarios?

Just my 2 pennies.  BTW, I like the new stand-up work the team is doing. :+1:
