### ISSUE TITLE
Clearer Design Review Communication Before Broadcast

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/corefx-standup#27]
Not sure if this would be the best place for this but…

On Tuesday a design review for `System.IO.Pipelines` was broadcast. While I'm really happy to see these again a lot of context for those watching was not given. While I agree that in the review is not the location for that, I think that information should be shared somehow.

cc: @terrajobst

**Comment by terrajobst** [comment]
Have you read this: https://github.com/dotnet/apireviews/tree/master/2017/07-11-System.IO.Pipelines?

It includes more information and also links to the spec.

**Comment by SamuelEnglard** [comment]
That is actually great! I think a link to that (or even just the speclet) in the video description would work.

**Comment by karelz** [comment]
Is there any particular action we want to take or is it ok to close?

**Comment by SamuelEnglard** [comment]
I think simply adding links in the stream description for background information is enough

**Comment by karelz** [comment]
@terrajobst can you please do that?
It would be great if you can also do it for the video we uploaded yesterday (just link the corefx-standup issue).

**Comment by terrajobst** [comment]
[Fixed](https://www.youtube.com/watch?v=IXg58zMsPug):

![image](https://user-images.githubusercontent.com/5169960/29948292-e57a0d5e-8e62-11e7-81cb-15a270d679d1.png)

**Comment by karelz** [comment]
Nit: I'd change it to "For notes **and background info / speclet**, take a look ...". The speclet is what @SamuelEnglard was interested in most.
