### ISSUE TITLE
CoreFX standup - Fri 2017/9/22 @ 10-11:30 PT

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx-standup#29]
### When

Fri 2017/9/22 @ 10am-11:30am PT ([get your time](http://www.thetimezoneconverter.com/?t=10:00%20am&tz=Pacific%20Time%20(PT)&))

### Agenda

* 10-11 - Selected topics info and discussion
    1. Brief info about what is happening in CoreFX repo, what are team's key priorities
    2. Topic: API review process & meetings (#10) - ~11 votes
    3. Topic: Larger community contributions (#12) - ~10 votes
* 11-11:30 - General Q&A and discussion

### Format

* The event will be on Google Hangouts, streamed live and recorded:
    * URL: https://www.youtube.com/watch?v=s7KnbMX6N_U
    * We will monitor the chat (you need to be signed in) and answer questions from there
* Any CoreFX contributor is welcome to join us

See [more details on standup format](https://github.com/dotnet/corefx-standup#format)

### Historical info

~~Please vote on date/time choice on top post:~
* ~~👍 if you plan to join us on this date & time~~
* ~~👎 if you can't make it~~

~~Please vote on [topics](https://github.com/dotnet/corefx-standup/issues?q=is%3Aopen+is%3Aissue+label%3ATopic). Feel free to suggest new ones (file a new issue).
We will pick 2-3 most-voted topics couple of days before the event and post them on this issue (you can subscribe to it).~~

**Comment by RheaAyase** [comment]
[Get Your Time](http://www.thetimezoneconverter.com/?t=10:00%20am&tz=Pacific%20Time%20(PT)&)

* 02:00 Tokyo
* 03:00 Sydney
* 10:00 PT
* 13:00 ET
* 17:00 UTC
* 19:00 CEST
* 22:30 India

**Comment by Drawaes** [comment]
I prefer the term GMT rather than UTC (mostly because I can see the laser from the Greenwich observatory going over my house our my window :P)

**Comment by benaadams** [comment]
GMT and UTC aren't interchangeable, they can differ by half a second

**Comment by Drawaes** [comment]
GMT was first... ;)

**Comment by karelz** [comment]
Thanks @RheaAyase! I planned to do something like that and then forgot before posting it ... I added the link to top post.

**Comment by jongalloway** [comment]
<a id="fl_ical" href="http://addtocalendar.com/atc/ical?f=m&e[0][date_start]=2017-09-22%2010%3A00%3A00&e[0][date_end]=2017-09-22%2013%3A00%3A00&e[0][timezone]=America%2FTijuana&e[0][title]=CoreFX%20standup&e[0][description]=See%20https%3A%2F%2Fgithub.com%2Fdotnet%2Fcorefx-standup%2Fissues%2F29%20for%20details&e[0][location]=Online&e[0][organizer]=Karel%20Zikmund&e[0][organizer_email]=Karel.Zikmund%40microsoft.com&e[0][privacy]=public" target="_blank">iCalendar</a> &nbsp;•&nbsp; <a id="fl_google" href="http://addtocalendar.com/atc/google?f=m&e[0][date_start]=2017-09-22%2010%3A00%3A00&e[0][date_end]=2017-09-22%2013%3A00%3A00&e[0][timezone]=America%2FTijuana&e[0][title]=CoreFX%20standup&e[0][description]=See%20https%3A%2F%2Fgithub.com%2Fdotnet%2Fcorefx-standup%2Fissues%2F29%20for%20details&e[0][location]=Online&e[0][organizer]=Karel%20Zikmund&e[0][organizer_email]=Karel.Zikmund%40microsoft.com&e[0][privacy]=public" target="_blank">Google Calendar</a> &nbsp;•&nbsp; <a id="fl_outlook" href="http://addtocalendar.com/atc/outlook?f=m&e[0][date_start]=2017-09-22%2010%3A00%3A00&e[0][date_end]=2017-09-22%2013%3A00%3A00&e[0][timezone]=America%2FTijuana&e[0][title]=CoreFX%20standup&e[0][description]=See%20https%3A%2F%2Fgithub.com%2Fdotnet%2Fcorefx-standup%2Fissues%2F29%20for%20details&e[0][location]=Online&e[0][organizer]=Karel%20Zikmund&e[0][organizer_email]=Karel.Zikmund%40microsoft.com&e[0][privacy]=public" target="_blank">Outlook</a> &nbsp;•&nbsp; <a id="fl_outlookonline" href="http://addtocalendar.com/atc/outlookonline?f=m&e[0][date_start]=2017-09-22%2010%3A00%3A00&e[0][date_end]=2017-09-22%2013%3A00%3A00&e[0][timezone]=America%2FTijuana&e[0][title]=CoreFX%20standup&e[0][description]=See%20https%3A%2F%2Fgithub.com%2Fdotnet%2Fcorefx-standup%2Fissues%2F29%20for%20details&e[0][location]=Online&e[0][organizer]=Karel%20Zikmund&e[0][organizer_email]=Karel.Zikmund%40microsoft.com&e[0][privacy]=public" target="_blank">Outlook Online</a> &nbsp;•&nbsp; <a id="fl_yahoo" href="http://addtocalendar.com/atc/yahoo?f=m&e[0][date_start]=2017-09-22%2010%3A00%3A00&e[0][date_end]=2017-09-22%2013%3A00%3A00&e[0][timezone]=America%2FTijuana&e[0][title]=CoreFX%20standup&e[0][description]=See%20https%3A%2F%2Fgithub.com%2Fdotnet%2Fcorefx-standup%2Fissues%2F29%20for%20details&e[0][location]=Online&e[0][organizer]=Karel%20Zikmund&e[0][organizer_email]=Karel.Zikmund%40microsoft.com&e[0][privacy]=public" target="_blank">Yahoo! Calendar</a>

Some add to calendar links (if they don't work blame https://addtocalendar.com/)

**Comment by mazong1123** [comment]
01:00 China :(

**Comment by RheaAyase** [comment]
> 01:00 China

Yes, there is gonna be night somewhere in the world, and 1:00 in the morning is very nice and early time. I had regular daily scrum meetings at 3-5am in the morning at some point.

**Comment by karelz** [comment]
Agenda updated in top post:
1. Brief info about what is happening in CoreFX repo, what are team's key priorities
2. Topic: API review process & meetings (#10) - ~11 votes
3. Topic: Larger community contributions (#12) - ~10 votes

BTW: We selected topics based on most votes (after de-duping previous votes "burned" into titles from previous round)

**Comment by karelz** [comment]
Link for watching the live stream added to the top post: https://www.youtube.com/watch?v=Tz-nzAf8nOI

**Comment by ChristopherHaws** [comment]
@karelz It would be nice to have this stream added to the .NET Foundation channel on YouTube (https://www.youtube.com/channel/UCiaZbznpWV1o-KLxj8zqR6A) so that we don't have to subscribe to a bunch of channels to get notified of the different standups. I believe that the ASP.NET Core team started streaming theirs there last week. :)

**Comment by karelz** [comment]
@ChristopherHaws yes, good feedback, thanks!
I did research that earlier this week (BTW: There is no ASP.NET sub-channel, so I am not sure how exactly that works/will work). We also talked about it with @terrajobst and the conclusion is that we need to consolidate those things. We didn't see a way to make it happen for this one. I expect that the next one will be in the "right place".

**Comment by mazong1123** [comment]
> The event will be on Google Hangouts

Are we going to send the join link here before the event starting?

**Comment by karelz** [comment]
@mazong1123 no, the plan is to share only the stream link above. There is chat for questions.
Last time we had everyone joining in with audio and no one wanted to use it. The chat worked pretty well for questions, so we will stick with that approach now.

**Comment by karelz** [comment]
Just FYI: We updated the link to the recording to https://www.youtube.com/watch?v=s7KnbMX6N_U (we hit technical difficulties when trying to stream on the original one ... sorry!)
