### ISSUE TITLE
Testing CircuitBreaker

### ISSUE THREAD

**Issue by shagilt** [dotnet/corefx-standup#30]
Sometime, my UT is failing because state is not reset to HalfOpen from Open. We are emitting metrics and logs during this phase and i wants to validate this in my UT.
For my UT, I have configured durationOfBreak as 1 sec. Is there a different approach to  test this? Do you think 1 sec is too low(though it is UT)?

**Comment by karelz** [comment]
@shagilt I think you have accidentally posted in the wrong repo ... this is off-topic here. It is not even clear to me about which product/library you're talking.
Closing.

**Comment by shagilt** [comment]
Yes, I am sorry.
