### ISSUE TITLE
Why Google Hangouts?

### ISSUE THREAD

**Issue by shmuelie** [dotnet/corefx-standup#6]
It only works in Chrome/Chromium! Skype/Lync/S4B/ANYTHING is better 😄 
(I don't hate Hangouts as much as having to install a browser for just this)

**Comment by RheaAyase** [comment]
Calling-in is not an option for someone with retarded voice, to not mention that insane bill afterwards. It is common knowledge that Skype is 99% useless, please, lets not ever even consider that.

**Comment by shaggygi** [comment]
@karelz you might want to ping @shanselman as they are reviewing options for the live.asp.net show.

**Comment by karelz** [comment]
@shaggygi we are already discussing that in that group.
