### ISSUE TITLE
Topic: State of tooling

### ISSUE THREAD

**Issue by cwe1ss** [dotnet/corefx-standup#7]
I'd love to have a discussion someday about the state/vision of tooling and documentation around it. It's currently very complicated to setup CI scripts because there are quite a few bugs and cases that are not yet supported properly.

Some examples:
* VS2017 Build Tools don't play well with .NET Core Sdks: https://github.com/Microsoft/msbuild/issues/1697
* Restoring packages in "mixed" environments (e.g. Service Fabric) is weird because you need `nuget restore` and `dotnet restore`: https://github.com/dotnet/cli/issues/6029 (currently even a "won't-fix")
* Service Fabric doesn't yet support non-web .NET core projects: https://github.com/Azure/service-fabric-issues/issues/152
* `dotnet build` is [slow](https://github.com/dotnet/cli/issues/5918), [slow](https://github.com/Microsoft/msbuild/issues/2015), [slow](https://github.com/Microsoft/msbuild/issues/1276).
* `dotnet pack` doesn't work properly with version-suffix: https://github.com/NuGet/Home/issues/4337
* `dotnet publish` removed the `--no-build` switch: https://github.com/dotnet/cli/issues/5331

It seems like whenever I try to change my script, I run into a new problem. (Luckily, poor people like @NickCraver and @onovotny have already tried the same thing before me so there's already github issues for most of it :smile:)

Sure, all of this is (hopefully) being worked on and it will get better over time but I'm not really seeing the "big picture" here on when people should use `nuget.exe`, `msbuild.exe` vs `dotnet.exe`. Now that they all call each other in mysterious ways it's very hard to understand which tool supports what. 

My main concern here is that it is *very* hard to explain all of this to new developers, and it's also a big frustration/confusion point for them. 

I'd love to hear your opinions on how this will/should be improved in the future and tackle questions like
* Should `dotnet.exe` be 'the one to rule them all' and support legacy formats? 
* Which project types will move to the new project format and when? (e.g. Service Fabric)
* etc.

**Comment by cwe1ss** [comment]
@karelz fyi, I haven't created an issue for this somewhere else and I probably won't do so in the near future. Feel free to close this issue if you don't want to keep it open here.

**Comment by karelz** [comment]
Closing per last reply - we can reopen if people disagree
